---
docker:
  crane:
    list:
      - find . -name crane*\\.y* > .cranelist.txt
  compose:
    list:
      - find . -name docker-compose*\\.y*
  images:
  	pull:
		- beniz/deepdetect_${PROCESSOR_COMPUTATION_TYPE}
    - floydhub/dl-docker:${PROCESSOR_COMPUTATION_TYPE}